version: '2'

services:

  moodle_db:
    image: mariadb:10.2
    volumes:
      - './data/db:/var/lib/mysql'
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_ONETIME_PASSWORD: "yes"
      MYSQL_DATABASE: $MOODLE_DB_NAME
      MYSQL_USER: $MOODLE_DB_USER
      MYSQL_PASSWORD: $MOODLE_DB_PASSWORD

  moodle:
    image: ellakcy/moodle:mysql_maria_apache
    volumes:
      - './data/moodle:/var/moodledata:rw'
      - './data/moodle/www:/var/www/html:rw'
    ports:
      - '8082:80'
    links:
      - moodle_db
    environment:
      MOODLE_URL: $MOODLE_URL
      MOODLE_ADMIN: $MOODLE_ADMIN
      MOODLE_ADMIN_PASSWORD: $MOODLE_ADMIN_PASSWORD
      MOODLE_ADMIN_EMAIL: $MOODLE_ADMIN_EMAIL
      MOODLE_DB_TYPE: "mariadb"
      MOODLE_DB_HOST: "moodle_db"
      MOODLE_DB_USER: $MOODLE_DB_USER
      MOODLE_DB_PASSWORD: $MOODLE_DB_PASSWORD
      MOODLE_DB_NAME: $MOODLE_DB_NAME
      MOODLE_REVERSE_LB: $MOODLE_REVERSE_LB
      MOODLE_SSL: $MOODLE_SSL
      MOODLE_EMAIL_TYPE_QMAIL: $MOODLE_EMAIL_TYPE_QMAIL
      MOODLE_EMAIL_HOST: $MOODLE_EMAIL_HOST
